[package]
name = "ssbh_test"
version = "0.19.0"
edition = "2024"

[[bin]]
name = "ssbh_test"
path = "src/main.rs"

[[bin]]
name = "scan_nuanmb"
path = "src/scan_nuanmb.rs"

[dependencies]
ssbh_lib = { path = "../ssbh_lib" }
ssbh_data = { path = "../ssbh_data" }
globwalk = "0.9.1"
rayon = "1.8.1"
clap = { workspace = true, features = ["derive"] }
